apiVersion: v1
kind: ConfigMap
metadata:
  name: agents-operator-config
  namespace: accuknox-agents
data:
  conf.yaml: |-
    agent:
      - name: feeder-service
        container: 
        - resource:
          - type: cpu
            request:
              - multiplier: 50
              - upper-bound: 200000
            limit:
              - multiplier: 100
              - upper-bound: 200000
          - type: memory
            request:
              - multiplier: 2
              - upper-bound: 5
            limit:
              - multiplier: 2
              - upper-bound: 5
      - name: shared-informer-agent
        container: 
        - resource:
          - type: cpu
            request:
              - multiplier: 200
              - upper-bound: 200000
            limit:
              - multiplier: 200
              - upper-bound: 200000
          - type: memory
            request:
              - multiplier: 3
              - upper-bound: 5
            limit:
              - multiplier: 3
              - upper-bound: 5
      - name: policy-enforcement-agent
        container: 
        - resource:
          - type: cpu
            request:
              - multiplier: 300
              - upper-bound: 200000
            limit:
              - multiplier: 300
              - upper-bound: 200000
          - type: memory
            request:
              - multiplier: 4
              - upper-bound: 5
            limit:
              - multiplier: 4
              - upper-bound: 5
      - name: discovery-engine
        container: 
        - resource:
          - type: cpu
            request:
              - multiplier: 400
              - upper-bound: 200000
            limit:
              - multiplier: 400
              - upper-bound: 200000
          - type: memory
            request:
              - multiplier: 5
              - upper-bound: 5
            limit:
              - multiplier: 5
              - upper-bound: 5

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: agents-operator
#   namespace: accuknox-agents
# spec:
#   selector:
#     matchLabels:
#       app: agents-operator
#   template:
#     metadata:
#       labels:
#         app: agents-operator
#     spec:
#       containers:
#       - name: agents-operator
#         image: accuknox/agents-operator:latest
#         imagePullPolicy: Never
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
