apiVersion: v1
kind: Namespace
metadata:
  name: accuknox-agents
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agents-operator-config
  namespace: accuknox-agents
data:
  conf.yaml: |-
    agent:
      - name: feeder-service
        container: 
        - resource:
          - type: cpu
            request:
              - value: (n/5 + 1)*50
              - upper-bound: 5000
            limit:
              - value: (n/5 + 1)*100
              - upper-bound: 10000
          - type: memory
            request:
              - value: (n/5 + 1)*100
              - upper-bound: 10000
            limit:
              - value: (n/5 + 1)*200
              - upper-bound: 20000
        chartname: accuknox-agents-dev/feeder-service-chart
      - name: shared-informer-agent
        container: 
        - resource:
          - type: cpu
            request:
              - value: (n/5 + 1)*20
              - upper-bound: 2000
            limit:
              - value: (n/5 + 1)*50
              - upper-bound: 5000
          - type: memory
            request:
              - value: (n/5 + 1)*50
              - upper-bound: 5000
            limit:
              - value: (n/5 + 1)*100
              - upper-bound: 10000
        chartname: accuknox-agents-dev/shared-informer-agent-chart
      - name: policy-enforcement-agent
        container: 
        - resource:
          - type: cpu
            request:
              - value: (n/5 + 1)*10
              - upper-bound: 1000
            limit:
              - value: (n/5 + 1)*30
              - upper-bound: 3000
          - type: memory
            request:
              - value: (n/5 + 1)*20
              - upper-bound: 2000
            limit:
              - value: (n/5 + 1)*50
              - upper-bound: 5000
        chartname:  accuknox-agents-dev/policy-enforcement-agent-chart
      - name: discovery-engine
        container: 
        - resource:
          - type: cpu
            request:
              - value: (n/5 + 1)*100
              - upper-bound: 10000
            limit:
              - value: (n/5 + 1)*200
              - upper-bound: 20000
          - type: memory
            request:
              - value: (n/5 + 1)*100
              - upper-bound: 10000
            limit:
              - value: (n/5 + 1)*200
              - upper-bound: 20000
        chartname: accuknox-agents-dev/discovery-engine-agent-chart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-operator
  namespace: accuknox-agents
  labels:
    deployment: agents-operator
spec:
  selector:
    matchLabels:
      app: agents-operator
  template:
    metadata:
      labels:
        app: agents-operator
    spec:
      serviceAccountName: agents-operator-sa
      containers:
      - image: accuknox/agents-operator:latest
        imagePullPolicy: Always
        name: agents-operator
        env:
          - name: tenant_id
            value: "0"
          - name: workspace_id
            value: "0"
          - name: cluster_name
            value: "default"
          - name: cluster_id
            value: "0"
          - name: helm_repo
            value: "accuknox-agents-dev"
          - name: helm_repo_url
            value: "https://USERNAME:PASSWORD@agents.accuknox.com/repository/accuknox-agents-dev"
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /conf
            name: config-volume
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: agents-operator-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agents-operator-sa
  namespace: accuknox-agents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agents-operator-role
rules:
- apiGroups: ["*"] 
  resources: [ "nodes", "configmaps", "pods", "namespaces", "endpoints"]
  verbs: [ "get", "list", "watch", "create", "delete", "update"]
- apiGroups: ["*"] 
  resources: [ "deployments"]
  verbs: [ "create", "get", "list", "watch", "patch"]
- apiGroups: ["*"]
  resources: ["clusterroles", "clusterrolebindings", "serviceaccounts", "secrets", "roles", "services", "rolebindings", "horizontalpodautoscalers"]
  verbs: ["get", "update", "create", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agents-operator-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agents-operator-role
subjects:
- kind: ServiceAccount
  name: agents-operator-sa
  namespace: accuknox-agents
