{{- define "imagePullSecret" }}
{{- with .Values.props }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .docker_repo_host .docker_repo_username .docker_repo_password (printf "%s:%s" .docker_repo_username .docker_repo_password | b64enc) | b64enc }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: imagepull
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}