agent:
- name: feeder-service
  container: 
  - resource:
    - type: cpu
      request:
        - value: (n/5 + 1)*50
        - upper-bound: 5000
      limit:
        - value: (n/5 + 1)*100
        - upper-bound: 10000
    - type: memory
      request:
        - value: (n/5 + 1)*100
        - upper-bound: 10000
      limit:
        - value: (n/5 + 1)*200
        - upper-bound: 20000
  chartname: accuknox-agents-dev/feeder-service-chart
- name: shared-informer-agent
  container: 
  - resource:
    - type: cpu
      request:
        - value: (n/5 + 1)*20
        - upper-bound: 2000
      limit:
        - value: (n/5 + 1)*50
        - upper-bound: 5000
    - type: memory
      request:
        - value: (n/5 + 1)*50
        - upper-bound: 5000
      limit:
        - value: (n/5 + 1)*100
        - upper-bound: 10000
  chartname: accuknox-agents-dev/shared-informer-agent-chart
- name: policy-enforcement-agent
  container: 
  - resource:
    - type: cpu
      request:
        - value: (n/5 + 1)*10
        - upper-bound: 1000
      limit:
        - value: (n/5 + 1)*30
        - upper-bound: 3000
    - type: memory
      request:
        - value: (n/5 + 1)*20
        - upper-bound: 2000
      limit:
        - value: (n/5 + 1)*50
        - upper-bound: 5000
  chartname:  accuknox-agents-dev/policy-enforcement-agent-chart
- name: discovery-engine
  container:
  - resource:
    - type: cpu
      request:
        - value: (n/5 + 1)*100
        - upper-bound: 10000
      limit:
        - value: (n/5 + 1)*200
        - upper-bound: 20000
    - type: memory
      request:
        - value: (n/5 + 1)*100
        - upper-bound: 10000
      limit:
        - value: (n/5 + 1)*200
        - upper-bound: 20000
  chartname: accuknox-agents-dev/discovery-engine-agent-chart
  