name: ci-latest-release

on:
  push:
    branches:
      - "main"
    paths:
      - "cmd/**"
      - "pkg/**"
      - ".github/workflows/ci-latest-release.yml"

jobs:
  build:
    name: Create latest release
    if: github.repository == 'accuknox/agents-operator'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: v1.19

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push image to Docker
        run: make all && make container && make push
